//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTSolution {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VTSolution.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bản Quyền.
        /// </summary>
        public static string BanQuyen {
            get {
                return ResourceManager.GetString("BanQuyen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Con Số Sự Kiện.
        /// </summary>
        public static string Conso {
            get {
                return ResourceManager.GetString("Conso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh Sách.
        /// </summary>
        public static string danhsach {
            get {
                return ResourceManager.GetString("danhsach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh Sách Khách Hàng.
        /// </summary>
        public static string Danhsachkhachhang {
            get {
                return ResourceManager.GetString("Danhsachkhachhang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa Chỉ.
        /// </summary>
        public static string Diachi {
            get {
                return ResourceManager.GetString("Diachi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điện Thoại.
        /// </summary>
        public static string Dienthoai {
            get {
                return ResourceManager.GetString("Dienthoai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đối Tác.
        /// </summary>
        public static string Doitac {
            get {
                return ResourceManager.GetString("Doitac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đồng Hành Cùng Song Ân.
        /// </summary>
        public static string DongHanh {
            get {
                return ResourceManager.GetString("DongHanh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dự Án.
        /// </summary>
        public static string duan {
            get {
                return ResourceManager.GetString("duan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Emai {
            get {
                return ResourceManager.GetString("Emai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Về Chúng Tôi.
        /// </summary>
        public static string Gioithieu {
            get {
                return ResourceManager.GetString("Gioithieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giờ làm việc.
        /// </summary>
        public static string GioLam {
            get {
                return ResourceManager.GetString("GioLam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi.
        /// </summary>
        public static string Gui {
            get {
                return ResourceManager.GetString("Gui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình Ảnh.
        /// </summary>
        public static string HinhAnh {
            get {
                return ResourceManager.GetString("HinhAnh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình Ảnh Hoạt Động.
        /// </summary>
        public static string HoatDong {
            get {
                return ResourceManager.GetString("HoatDong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ Nói Về Chúng Tôi.
        /// </summary>
        public static string HoNoi {
            get {
                return ResourceManager.GetString("HoNoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hồ Sơ Năng Lực.
        /// </summary>
        public static string HoSoNangLuc {
            get {
                return ResourceManager.GetString("HoSoNangLuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ Tên.
        /// </summary>
        public static string Hoten {
            get {
                return ResourceManager.GetString("Hoten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hỗ Trợ.
        /// </summary>
        public static string HoTro {
            get {
                return ResourceManager.GetString("HoTro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sự Khác Biệt.
        /// </summary>
        public static string KhacBiet {
            get {
                return ResourceManager.GetString("KhacBiet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách Hàng.
        /// </summary>
        public static string KhachHang {
            get {
                return ResourceManager.GetString("KhachHang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khu Vực.
        /// </summary>
        public static string Khuvuc {
            get {
                return ResourceManager.GetString("Khuvuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lịch Sử Hình Thành Và Phát Triển.
        /// </summary>
        public static string Lichsuhinhthanh {
            get {
                return ResourceManager.GetString("Lichsuhinhthanh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên Hệ.
        /// </summary>
        public static string Lienhe {
            get {
                return ResourceManager.GetString("Lienhe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản Phẩm Liên Quan.
        /// </summary>
        public static string LienQuan {
            get {
                return ResourceManager.GetString("LienQuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người Liên Hệ.
        /// </summary>
        public static string Nguoilienhe {
            get {
                return ResourceManager.GetString("Nguoilienhe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nguyên Tắc Hoạt Động.
        /// </summary>
        public static string Nguyentac {
            get {
                return ResourceManager.GetString("Nguyentac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đội Ngũ Nhân Sự.
        /// </summary>
        public static string NhanSu {
            get {
                return ResourceManager.GetString("NhanSu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản Phẩm .
        /// </summary>
        public static string Sanpham {
            get {
                return ResourceManager.GetString("Sanpham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phần Mềm Quản Lý Bệnh Viện .
        /// </summary>
        public static string SPNoiBat {
            get {
                return ResourceManager.GetString("SPNoiBat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sứ Mệnh.
        /// </summary>
        public static string SuMenh {
            get {
                return ResourceManager.GetString("SuMenh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tầm Nhìn.
        /// </summary>
        public static string Tamnhin {
            get {
                return ResourceManager.GetString("Tamnhin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông Điệp.
        /// </summary>
        public static string ThongDiep {
            get {
                return ResourceManager.GetString("ThongDiep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin bắt buộc.
        /// </summary>
        public static string Thongtinbatbuoc {
            get {
                return ResourceManager.GetString("Thongtinbatbuoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chủ Đề.
        /// </summary>
        public static string TieuDe {
            get {
                return ResourceManager.GetString("TieuDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kết quả tìm kiếm.
        /// </summary>
        public static string tim {
            get {
                return ResourceManager.GetString("tim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tỉnh Thành.
        /// </summary>
        public static string Tinhthanh {
            get {
                return ResourceManager.GetString("Tinhthanh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin Khác.
        /// </summary>
        public static string TinKhac {
            get {
                return ResourceManager.GetString("TinKhac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin Mới.
        /// </summary>
        public static string Tinmoi {
            get {
                return ResourceManager.GetString("Tinmoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin Tức.
        /// </summary>
        public static string TinTuc {
            get {
                return ResourceManager.GetString("TinTuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin Tức Nội Bộ.
        /// </summary>
        public static string Tintucnoibo {
            get {
                return ResourceManager.GetString("Tintucnoibo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string Tintucvideo {
            get {
                return ResourceManager.GetString("Tintucvideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin tức xã hội.
        /// </summary>
        public static string Tintucxahoi {
            get {
                return ResourceManager.GetString("Tintucxahoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string tongquan {
            get {
                return ResourceManager.GetString("tongquan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang Chủ.
        /// </summary>
        public static string Trangchu {
            get {
                return ResourceManager.GetString("Trangchu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trụ Sở Chính.
        /// </summary>
        public static string Truso {
            get {
                return ResourceManager.GetString("Truso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuyển Dụng.
        /// </summary>
        public static string Tuyendung {
            get {
                return ResourceManager.GetString("Tuyendung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vì Sao Chọn Chúng Tôi.
        /// </summary>
        public static string ViSao {
            get {
                return ResourceManager.GetString("ViSao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vị trí.
        /// </summary>
        public static string vitri {
            get {
                return ResourceManager.GetString("vitri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem Chi Tiết.
        /// </summary>
        public static string Xemchitiet {
            get {
                return ResourceManager.GetString("Xemchitiet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        public static string Xoa {
            get {
                return ResourceManager.GetString("Xoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung yêu cầu .
        /// </summary>
        public static string Ykien {
            get {
                return ResourceManager.GetString("Ykien", resourceCulture);
            }
        }
    }
}
