WHILE EXISTS(SELECT 1 FROM @V_TB_GHITANGCT)
BEGIN
	SELECT TOP 1 @V_ROWID = ROWID, @V_TAISANID = TAISANID, @V_NGAYBATDAUSUDUNG = NGAYBATDAUSUDUNG, @V_PHONGBANID = PHONGBANID, @V_NHANVIENID=NHANVIENID,@V_SOLUONG = SOLUONG FROM @V_TB_GHITANGCT

	IF EXISTS(SELECT 1 FROM dbo.TheoDoi WHERE TaiSanId = @V_TAISANID AND NhanVienId = @V_NHANVIENID AND PhongBanId = @V_PHONGBANID)
	BEGIN
		UPDATE dbo.TheoDoi SET SLTang = SLTang + @V_SOLUONG WHERE TaiSanId = @V_TAISANID AND NhanVienId = @V_NHANVIENID AND PhongBanId = @V_PHONGBANID
	END
	ELSE
	BEGIN
		INSERT dbo.TheoDoi
				( 
					TaiSanId ,			NgayTrangCap ,			NgayBatDauSuDung ,		PhongBanId ,			
					NhanVienId ,		SLTon ,					SLTang ,				SLGiam
				)
		SELECT		@V_TAISANID			,@V_NGAYBATDAUSUDUNG	,@V_NGAYBATDAUSUDUNG	,@V_PHONGBANID
					,@V_NHANVIENID		,0						,@V_SOLUONG				,0
	END

	DELETE @V_TB_GHITANGCT WHERE ROWID = @V_ROWID
	SELECT @V_ROWID = NULL,@V_TAISANID = NULL,@V_NGAYBATDAUSUDUNG = NULL,@V_PHONGBANID = NULL,@V_NHANVIENID = NULL,@V_SOLUONG = NULL
END