//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTSolution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AboutU
    {
        public int Id { get; set; }
        public string Vi_Company { get; set; }
        public string Email { get; set; }
        public string Fax { get; set; }
        public string Phone { get; set; }
        public string HotLine { get; set; }
        public string Slogan { get; set; }
        public string Facebook { get; set; }
        public string Twitter { get; set; }
        public string Google { get; set; }
        public string Address { get; set; }
        public string Description { get; set; }
        public string EmailSent { get; set; }
        public string EmailReceive { get; set; }
        public string EmailPassword { get; set; }
        public string Skype { get; set; }
        public string Websites { get; set; }
        public string Eng_Slogan { get; set; }
        public string HomePageTitle { get; set; }
        public string HomePageDiscription { get; set; }
        public string HomePageKeywords { get; set; }
        public string MetaCopyRight { get; set; }
        public string MetaAbstract { get; set; }
        public string MetaAuthor { get; set; }
        public string ImagePath { get; set; }
        public bool IsDisable { get; set; }
        public string LinkPopUp { get; set; }
        public string Longtitude { get; set; }
        public string Latitude { get; set; }
        public string ImagePath3 { get; set; }
        public string Eng_Company { get; set; }
        public string Eng_Address { get; set; }
        public string SloganStaff { get; set; }
        public string SloganAlbum { get; set; }
        public string SloganReason { get; set; }
        public string Eng_SloganStaff { get; set; }
        public string Eng_SloganAlbum { get; set; }
        public string Eng_SloganReason { get; set; }
        public string Vi_Product { get; set; }
        public string Eng_Product { get; set; }
        public string Linkedin { get; set; }
        public string Instagram { get; set; }
        public string Ja_Slogan { get; set; }
        public string Ja_Company { get; set; }
        public string Ja_Address { get; set; }
        public string Ja_SloganStaff { get; set; }
        public string Ja_SloganAlbum { get; set; }
        public string Ja_SloganReason { get; set; }
        public string Ja_Product { get; set; }
    }
}
