//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTSolution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banner
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string ImagePath { get; set; }
        public bool IsDisable { get; set; }
        public bool IsDelete { get; set; }
        public string Link { get; set; }
        public bool IsReason { get; set; }
        public string Vi_Caption { get; set; }
        public string Eng_Caption { get; set; }
        public int OrderBy { get; set; }
        public bool IsDistribution { get; set; }
        public bool IsLogo { get; set; }
        public string ImagePath2 { get; set; }
        public string Link2 { get; set; }
        public string Name2 { get; set; }
        public bool Isbanner { get; set; }
        public bool IsPartner { get; set; }
        public bool IsLearn { get; set; }
        public bool IsWork { get; set; }
        public bool IsPlay { get; set; }
        public bool IsLydo { get; set; }
        public string Ja_Caption { get; set; }
        public string ImagePath3 { get; set; }
        public string Link3 { get; set; }
        public string Name3 { get; set; }
    }
}
