//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTSolution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Email
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email1 { get; set; }
        public string Content { get; set; }
        public string Phone { get; set; }
        public string DateCreate { get; set; }
        public string Company { get; set; }
        public string Project { get; set; }
    }
}
