//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTSolution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feature
    {
        public Feature()
        {
            this.Digitals = new HashSet<Digital>();
            this.FeatureSons = new HashSet<FeatureSon>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Vi_Content { get; set; }
        public string Eng_Content { get; set; }
        public string Ja_Content { get; set; }
    
        public virtual ICollection<Digital> Digitals { get; set; }
        public virtual ICollection<FeatureSon> FeatureSons { get; set; }
    }
}
