//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTSolution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        public File()
        {
            this.ProductFiles = new HashSet<ProductFile>();
        }
    
        public int Id { get; set; }
        public string Vi_Name { get; set; }
        public string Eng_Name { get; set; }
        public string LinkDownload { get; set; }
        public bool IsDelete { get; set; }
        public bool IsDisable { get; set; }
        public Nullable<int> Downloaded { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public string FileSize { get; set; }
        public int OrderBy { get; set; }
        public string Url { get; set; }
        public string LinkDownload2 { get; set; }
        public string Url2 { get; set; }
    
        public virtual ICollection<ProductFile> ProductFiles { get; set; }
    }
}
