//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTSolution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public Group()
        {
            this.News = new HashSet<News>();
        }
    
        public int Id { get; set; }
        public string GroupName { get; set; }
        public string Eng_GroupName { get; set; }
        public int OrderBy { get; set; }
        public string Ja_GroupName { get; set; }
    
        public virtual ICollection<News> News { get; set; }
    }
}
