//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTSolution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupProduct
    {
        public GroupProduct()
        {
            this.GroupProductSons = new HashSet<GroupProductSon>();
        }
    
        public int Id { get; set; }
        public string Vi_Name { get; set; }
        public string Eng_Name { get; set; }
        public bool IsDelete { get; set; }
        public string ImagePath { get; set; }
        public int OrderBy { get; set; }
        public string Ja_Name { get; set; }
    
        public virtual ICollection<GroupProductSon> GroupProductSons { get; set; }
    }
}
