//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTSolution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupVideo
    {
        public GroupVideo()
        {
            this.Videos = new HashSet<Video>();
        }
    
        public int Id { get; set; }
        public string Vi_Name { get; set; }
        public string Eng_Name { get; set; }
        public bool IsIntroduce { get; set; }
        public Nullable<int> GroupBy { get; set; }
        public bool IsShowHome { get; set; }
        public int OrderBy { get; set; }
    
        public virtual ICollection<Video> Videos { get; set; }
    }
}
