//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTSolution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupImage
    {
        public GroupImage()
        {
            this.Images = new HashSet<Image>();
        }
    
        public int Id { get; set; }
        public string Vi_Name { get; set; }
        public string Eng_Name { get; set; }
        public string ImagePath { get; set; }
        public string Vi_Description { get; set; }
        public string Eng_Description { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public int OrderBy { get; set; }
        public Nullable<int> GRID { get; set; }
        public bool IsWork { get; set; }
        public bool IsLearn { get; set; }
        public bool IsPlay { get; set; }
    
        public virtual ICollection<Image> Images { get; set; }
    }
}
