//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTSolution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log_Backend
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public string ErrorLog { get; set; }
        public string Feature { get; set; }
        public string Controller { get; set; }
    }
}
