//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTSolution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuAdmin
    {
        public int Id { get; set; }
        public string MenuName { get; set; }
        public string Controller { get; set; }
        public string View { get; set; }
        public Nullable<int> Sequence { get; set; }
        public bool IsParent { get; set; }
        public Nullable<int> ParentId { get; set; }
        public bool IsDisable { get; set; }
    }
}
