//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTSolution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Music
    {
        public int Id { get; set; }
        public string LinkDownload { get; set; }
        public string Content { get; set; }
        public Nullable<int> View { get; set; }
        public string Name { get; set; }
    }
}
