//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTSolution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int Id { get; set; }
        public string Vi_Title { get; set; }
        public string Eng_Title { get; set; }
        public string Vi_Description { get; set; }
        public string Eng_Description { get; set; }
        public string Vi_Content { get; set; }
        public string Eng_Content { get; set; }
        public bool IsHot { get; set; }
        public bool IsShowHome { get; set; }
        public bool IsDisable { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<int> GroupId { get; set; }
        public string ImagePath { get; set; }
        public Nullable<bool> IsSecurity { get; set; }
        public Nullable<bool> IsTechnology { get; set; }
        public Nullable<int> OrderBy { get; set; }
        public string ImagePath2 { get; set; }
        public string Ja_Title { get; set; }
        public string Ja_Description { get; set; }
        public string Ja_Content { get; set; }
        public Nullable<int> View { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<bool> IsNumber { get; set; }
        public string Number { get; set; }
        public string Vi_MetaTitle { get; set; }
        public string Vi_MetaDescription { get; set; }
        public string Vi_MetaKeyword { get; set; }
        public string Eng_MetaTitle { get; set; }
        public string Eng_MetaDescription { get; set; }
        public string Eng_MetaKeyword { get; set; }
        public string SeVi { get; set; }
        public string SeEn { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual Project Project { get; set; }
    }
}
