//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTSolution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Digitals = new HashSet<Digital>();
            this.ProductFiles = new HashSet<ProductFile>();
            this.ProductImages = new HashSet<ProductImage>();
        }
    
        public int Id { get; set; }
        public string Vi_Name { get; set; }
        public string Eng_Name { get; set; }
        public string ImagePath { get; set; }
        public string Vi_Description { get; set; }
        public string Eng_Description { get; set; }
        public string Vi_Content { get; set; }
        public string Eng_Content { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
    
        public virtual ICollection<Digital> Digitals { get; set; }
        public virtual ICollection<ProductFile> ProductFiles { get; set; }
        public virtual ICollection<ProductImage> ProductImages { get; set; }
    }
}
