//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTSolution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.News = new HashSet<News>();
            this.ProjectImages = new HashSet<ProjectImage>();
            this.Videos = new HashSet<Video>();
        }
    
        public int Id { get; set; }
        public string Vi_Title { get; set; }
        public string Eng_Title { get; set; }
        public string Vi_Description { get; set; }
        public string Eng_Description { get; set; }
        public string Vi_Content { get; set; }
        public string Eng_Content { get; set; }
        public bool IsHot { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public string ImagePath { get; set; }
        public int OrderBy { get; set; }
        public string Vi_MetaTitle { get; set; }
        public string Vi_MetaDescription { get; set; }
        public string Vi_MetaKeyword { get; set; }
        public string Eng_MetaTitle { get; set; }
        public string Eng_MetaDescription { get; set; }
        public string Eng_MetaKeyword { get; set; }
        public string SeVi { get; set; }
        public string SeEn { get; set; }
        public string Ja_Title { get; set; }
        public string Ja_Description { get; set; }
        public string Ja_Content { get; set; }
        public string SeJa { get; set; }
    
        public virtual ICollection<News> News { get; set; }
        public virtual ICollection<ProjectImage> ProjectImages { get; set; }
        public virtual ICollection<Video> Videos { get; set; }
    }
}
