//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTSolution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recruitment
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public Nullable<int> GroupId { get; set; }
        public string Content { get; set; }
        public string Imagepath { get; set; }
        public string LinkDownload { get; set; }
        public string Eng_Name { get; set; }
        public string Eng_Address { get; set; }
        public string Eng_Content { get; set; }
        public string Description { get; set; }
        public string Eng_Description { get; set; }
        public string Vi_MetaTitle { get; set; }
        public string Vi_MetaDescription { get; set; }
        public string Vi_MetaKeyword { get; set; }
        public string Eng_MetaTitle { get; set; }
        public string Eng_MetaDescription { get; set; }
        public string Eng_MetaKeyword { get; set; }
    }
}
