//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTSolution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTinUngVien
    {
        public int Id { get; set; }
        public string HoTen { get; set; }
        public System.DateTime NgaySinh { get; set; }
        public string DiaChi { get; set; }
        public string Email { get; set; }
        public string KyNang { get; set; }
        public string GioiThieu { get; set; }
        public int Nam { get; set; }
        public string TenTruong { get; set; }
        public string ChuyenNganh { get; set; }
        public string DienThoai { get; set; }
    }
}
