//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTSolution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video
    {
        public int Id { get; set; }
        public string Vi_Name { get; set; }
        public string Eng_Name { get; set; }
        public string Link { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<int> GroupId { get; set; }
        public bool IsHot { get; set; }
        public Nullable<int> Viewed { get; set; }
        public string Vi_Content { get; set; }
        public string Eng_Content { get; set; }
        public int OrderBy { get; set; }
        public bool IsShowHome { get; set; }
        public bool IsIntroduce { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public string ImagePath { get; set; }
    
        public virtual GroupVideo GroupVideo { get; set; }
        public virtual Project Project { get; set; }
    }
}
