//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTSolution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visitor
    {
        public int VisitorID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> Visitors { get; set; }
    }
}
