ALTER proc [dbo].[sp_GhiTang_DeleteGhiTangById]
	@GhiTangId INT
as
BEGIN
	Declare @ErrMsg nvarchar(max)
	DECLARE @V_TB_GHITANGCT TABLE
	(
		ROWID INT IDENTITY(1,1),
		TAISANID INT,
		NGAYBATDAUSUDUNG DATETIME,
		PHONGBANID INT,
		NHANVIENID INT,
		SOLUONG NUMERIC(18,4)
	)
	DECLARE @V_ROWID INT ,
			@V_TAISANID INT,
			@V_NGAYBATDAUSUDUNG DATETIME,
			@V_PHONGBANID INT,
			@V_NHANVIENID INT,
			@V_SOLUONG NUMERIC(18,4),
			@V_NGAYGHITANG DATETIME,
			@V_SOCHUNGTU NVARCHAR(50),
			@V_DUYETID INT,
			@V_CHOTNAM INT,
			@V_COSOID INT

	SELECT @V_NGAYGHITANG = NgayGhiTang, @V_SOCHUNGTU = SoChungTu, @V_DUYETID = DuyetId, @V_COSOID = CoSoId FROM dbo.GhiTang WHERE GhiTangId = @GhiTangId

	SELECT @V_CHOTNAM = TrangThai FROM dbo.KhoaSoLieu WHERE Nam = YEAR(@V_NGAYGHITANG) AND CoSoId = @V_COSOID

	-- check chốt năm + duyệt
	IF (@V_DUYETID = 1 OR @V_CHOTNAM = 1)
	BEGIN
		SELECT -1 AS ID RETURN
	END
    
	BEGIN TRAN
		
		BEGIN TRY
			
			INSERT @V_TB_GHITANGCT( TAISANID ,NGAYBATDAUSUDUNG ,PHONGBANID ,NHANVIENID ,SOLUONG)
			SELECT GTCT.TaiSanId,GTCT.NgayBatDauSuDung,GTCT.PhongBanId,GTCT.NhanVienId,GTCT.SoLuong
			FROM dbo.GhiTangChiTiet GTCT WHERE GTCT.GhiTangId = @GhiTangId			

			WHILE EXISTS(SELECT 1 FROM @V_TB_GHITANGCT)
			BEGIN
				SELECT TOP 1 @V_ROWID = ROWID, @V_TAISANID = TAISANID, @V_NGAYBATDAUSUDUNG = NGAYBATDAUSUDUNG, @V_PHONGBANID = PHONGBANID, @V_NHANVIENID=NHANVIENID,@V_SOLUONG = SOLUONG FROM @V_TB_GHITANGCT

				IF EXISTS(SELECT 1 FROM dbo.TheoDoi WHERE TaiSanId = @V_TAISANID AND NhanVienId = @V_NHANVIENID AND PhongBanId = @V_PHONGBANID AND Nam = YEAR(@V_NGAYGHITANG))
				BEGIN

					UPDATE dbo.TheoDoi SET SLTang = SLTang - @V_SOLUONG WHERE TaiSanId = @V_TAISANID AND NhanVienId = @V_NHANVIENID AND PhongBanId = @V_PHONGBANID AND Nam = YEAR(@V_NGAYGHITANG)

					IF (SELECT SLTon + SLTang - SLGiam FROM dbo.TheoDoi WHERE TaiSanId = @V_TAISANID AND NhanVienId = @V_NHANVIENID AND PhongBanId = @V_PHONGBANID AND Nam = YEAR(@V_NGAYGHITANG)) < 0
					BEGIN	
						begin try rollback tran end try begin catch end CATCH
                        SELECT -1 AS ID,@V_SOCHUNGTU SOCHUNGTU
						RETURN
					END
					
				END
				

				DELETE @V_TB_GHITANGCT WHERE ROWID = @V_ROWID
				SELECT @V_ROWID = NULL,@V_TAISANID = NULL,@V_NGAYBATDAUSUDUNG = NULL,@V_PHONGBANID = NULL,@V_NHANVIENID = NULL,@V_SOLUONG = NULL
			END

			DELETE dbo.GhiTangChiTiet WHERE GhiTangId = @GhiTangId
			DELETE dbo.GhiTang WHERE GhiTangId = @GhiTangId
			
			SELECT @@ROWCOUNT

		END TRY
		BEGIN CATCH
			select @ErrMsg=ERROR_MESSAGE()
			raiserror(@ErrMsg,16,1)
			begin try rollback tran end try begin catch end catch
			return 
		END CATCH
	COMMIT TRAN
END
