//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nop.Web.Models.BaoHanh
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhoHangSanXuat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhoHangSanXuat()
        {
            this.KhoHangHoas = new HashSet<KhoHangHoa>();
        }
    
        public int HangSanXuatId { get; set; }
        public string MaHangSanXuat { get; set; }
        public string TenHangSanXuat { get; set; }
        public string MoTa { get; set; }
        public Nullable<int> NguoiTao { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string XoaYN { get; set; }
        public Nullable<int> CtrVersion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhoHangHoa> KhoHangHoas { get; set; }
    }
}
