//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nop.Web.Models.BaoHanh
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhoPhieuXuatChiTiet
    {
        public int PhieuXuatChiTietId { get; set; }
        public int PhieuXuatId { get; set; }
        public int HangHoaId { get; set; }
        public Nullable<decimal> GiaNhap { get; set; }
        public string LoHang { get; set; }
        public decimal SoLuong { get; set; }
        public decimal DonGia { get; set; }
        public Nullable<short> ThoiGianBaoHanh { get; set; }
        public string XoaYN { get; set; }
    
        public virtual KhoHangHoa KhoHangHoa { get; set; }
        public virtual KhoPhieuXuat KhoPhieuXuat { get; set; }
    }
}
