//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nop.Web.Models.BaoHanh
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhoPhieuXuat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhoPhieuXuat()
        {
            this.KhoPhieuXuatChiTiets = new HashSet<KhoPhieuXuatChiTiet>();
        }
    
        public int PhieuXuatId { get; set; }
        public string LoaiPhieu { get; set; }
        public Nullable<int> KhachHangId { get; set; }
        public string SoPhieu { get; set; }
        public string NguoiNhanHang { get; set; }
        public string SoDienThoai { get; set; }
        public string SoHoaDon { get; set; }
        public string Seri { get; set; }
        public Nullable<System.DateTime> NgayChungTu { get; set; }
        public string NoiDung { get; set; }
        public Nullable<int> TaiKhoanCo { get; set; }
        public Nullable<int> TaiKhoanNo { get; set; }
        public Nullable<int> TaiKhoanKho { get; set; }
        public Nullable<int> TaiKhoanGiaVon { get; set; }
        public int KhoXuat { get; set; }
        public Nullable<System.DateTime> NgayThanhToan { get; set; }
        public System.DateTime NgayXuat { get; set; }
        public Nullable<int> ThuKho { get; set; }
        public Nullable<int> NguoiGiaoHang { get; set; }
        public string DiaChi { get; set; }
        public string Hinh { get; set; }
        public string MaTrangThai { get; set; }
        public Nullable<decimal> ChiPhi { get; set; }
        public Nullable<decimal> ThueVAT { get; set; }
        public Nullable<decimal> TienThue { get; set; }
        public Nullable<decimal> ChietKhau { get; set; }
        public Nullable<int> NguoiTao { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string XoaYN { get; set; }
        public Nullable<int> CtrVersion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhoPhieuXuatChiTiet> KhoPhieuXuatChiTiets { get; set; }
    }
}
