//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nop.Web.Models.BaoHanh
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhoPhieuSery
    {
        public int Id { get; set; }
        public string Series { get; set; }
        public Nullable<short> ThoiGianBaoHanh { get; set; }
        public string SoPhieu { get; set; }
        public string MaHangHoa { get; set; }
        public Nullable<int> HangHoaId { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> NguoiTao { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string XoaYN { get; set; }
        public Nullable<int> CtrVersion { get; set; }
    }
}
