//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nop.Web.Models.BaoHanh
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MSSQL_QLDN_QLNS_DEMOEntities : DbContext
    {
        public MSSQL_QLDN_QLNS_DEMOEntities()
            : base("name=MSSQL_QLDN_QLNS_DEMOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<KhoHangHoa> KhoHangHoas { get; set; }
        public virtual DbSet<KhoHangSanXuat> KhoHangSanXuats { get; set; }
        public virtual DbSet<KhoPhieuSery> KhoPhieuSeries { get; set; }
        public virtual DbSet<KhoPhieuXuat> KhoPhieuXuats { get; set; }
        public virtual DbSet<KhoPhieuXuatChiTiet> KhoPhieuXuatChiTiets { get; set; }
    
        public virtual ObjectResult<sp_KhoPhieuBaoHanh_GetThongTinBySeries_Result> sp_KhoPhieuBaoHanh_GetThongTinBySeries(string sERIES, string lOGIN_ID, ObjectParameter mESSAGE)
        {
            var sERIESParameter = sERIES != null ?
                new ObjectParameter("SERIES", sERIES) :
                new ObjectParameter("SERIES", typeof(string));
    
            var lOGIN_IDParameter = lOGIN_ID != null ?
                new ObjectParameter("LOGIN_ID", lOGIN_ID) :
                new ObjectParameter("LOGIN_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_KhoPhieuBaoHanh_GetThongTinBySeries_Result>("sp_KhoPhieuBaoHanh_GetThongTinBySeries", sERIESParameter, lOGIN_IDParameter, mESSAGE);
        }
    }
}
