
// This file was automatically generated by the Dapper.FastCRUD T4 Template
// Do not make changes directly to this file - edit the template configuration instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `dbQLNSConnection`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `Data Source=192.168.1.201;Network Library=DBMSSOCN;Initial Catalog=QLTS;User ID=sa;Password=******;`
//     Include Views:          `True`

namespace SongAn.QLTS.Entity.QLTS.Entity
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the ThongTinKeKhai_Oto table.
    /// </summary>
	[Table("ThongTinKeKhai_Oto")]
	public partial class ThongTinKeKhaiOto
	{
	    public virtual int TaiSanId { get; set; }
	    public virtual string NhanHieu { get; set; }
	    public virtual string BienKiemSoat { get; set; }
	    public virtual decimal CongSuatXe { get; set; }
	    public virtual decimal TrongTai { get; set; }
	    public virtual string ChucDanh { get; set; }
	    public virtual string NguonGocXe { get; set; }
	    public virtual int LoaiXe { get; set; }
	    public virtual int HienTrangSuDung { get; set; }
	}

    /// <summary>
    /// A class which represents the ThongTinKeKhai_Tren500 table.
    /// </summary>
	[Table("ThongTinKeKhai_Tren500")]
	public partial class ThongTinKeKhaiTren500
	{
	    public virtual int TaiSanId { get; set; }
	    public virtual string KyHieu { get; set; }
	    public virtual int HienTrangSuDung { get; set; }
	}

    /// <summary>
    /// A class which represents the ThayDoiThongTin_Dat table.
    /// </summary>
	[Table("ThayDoiThongTin_Dat")]
	public partial class ThayDoiThongTinDat
	{
	    public virtual int ThayDoiThongTinId { get; set; }
	    public virtual string DiaChiCu { get; set; }
	    public virtual string GiayToCu { get; set; }
	    public virtual decimal DienTichCu { get; set; }
	    public virtual decimal LamTruSoCu { get; set; }
	    public virtual decimal CoSoHDSuNghiepCu { get; set; }
	    public virtual decimal NhaOCu { get; set; }
	    public virtual decimal ChoThueCu { get; set; }
	    public virtual decimal BoTrongCu { get; set; }
	    public virtual decimal BiLanChiemCu { get; set; }
	    public virtual decimal SuDungKhacCu { get; set; }
	}

    /// <summary>
    /// A class which represents the DeNghiTrangCapChiTiet table.
    /// </summary>
	[Table("DeNghiTrangCapChiTiet")]
	public partial class DeNghiTrangCapChiTiet
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int DeNghiChiTietId { get; set; }
	    public virtual int DeNghiId { get; set; }
	    public virtual string TenTaiSan { get; set; }
	    public virtual string MoTa { get; set; }
	    public virtual int LoaiId { get; set; }
	    public virtual decimal SoLuong { get; set; }
	    public virtual string DonViTinh { get; set; }
	    public virtual int PhuongThucId { get; set; }
	    public virtual DateTime NgayDeNghi { get; set; }
	    public virtual decimal? DuToan { get; set; }
	    public virtual decimal? DuToanDuocDuyet { get; set; }
	    public virtual string GhiChu { get; set; }
	}

    /// <summary>
    /// A class which represents the ThayDoiThongTin_Nha table.
    /// </summary>
	[Table("ThayDoiThongTin_Nha")]
	public partial class ThayDoiThongTinNha
	{
	    public virtual int ThayDoiThongTinId { get; set; }
	    public virtual string DiaChiCu { get; set; }
	    public virtual string GiayToCu { get; set; }
	    public virtual int CapHangCu { get; set; }
	    public virtual int SoTangCu { get; set; }
	    public virtual decimal NamSuDungCu { get; set; }
	    public virtual decimal DienTichCu { get; set; }
	    public virtual decimal TongDienTichSanCu { get; set; }
	    public virtual decimal LamTruSoCu { get; set; }
	    public virtual decimal CoSoHDSuNghiepCu { get; set; }
	    public virtual decimal NhaOCu { get; set; }
	    public virtual decimal ChoThueCu { get; set; }
	    public virtual decimal BoTrongCu { get; set; }
	    public virtual decimal BiLanChiemCu { get; set; }
	    public virtual decimal SuDungKhacCu { get; set; }
	}

    /// <summary>
    /// A class which represents the KhoPhieuNhap table.
    /// </summary>
	[Table("KhoPhieuNhap")]
	public partial class KhoPhieuNhap
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int KhoPhieuNhapId { get; set; }
	    public virtual int KhoTaiSanId { get; set; }
	    public virtual int NguonNganSachId { get; set; }
	    public virtual int NhaCungCapId { get; set; }
	    public virtual DateTime NgayNhap { get; set; }
	    public virtual string SoPhieu { get; set; }
	    public virtual string Seri { get; set; }
	    public virtual string SoHoaDon { get; set; }
	    public virtual DateTime? NgayHD { get; set; }
	    public virtual string BBKiem { get; set; }
	    public virtual int? ChietKhau { get; set; }
	    public virtual string NguoiGiao { get; set; }
	    public virtual string Loai { get; set; }
	    public virtual string TaiKhoanNo { get; set; }
	    public virtual string TaiKhoanCo { get; set; }
	    public virtual string NoiDung { get; set; }
	    public virtual int? CoSoId { get; set; }
	    public virtual int? NguoiTao { get; set; }
	    public virtual DateTime? NgayTao { get; set; }
	    public virtual int? CtrVersion { get; set; }
	}

    /// <summary>
    /// A class which represents the ThayDoiThongTin_Oto table.
    /// </summary>
	[Table("ThayDoiThongTin_Oto")]
	public partial class ThayDoiThongTinOto
	{
	    public virtual int ThayDoiThongTinId { get; set; }
	    public virtual string NhanHieuCu { get; set; }
	    public virtual string BienKiemSoatCu { get; set; }
	    public virtual decimal CongSuatXeCu { get; set; }
	    public virtual decimal TrongTaiCu { get; set; }
	    public virtual string ChucDanhCu { get; set; }
	    public virtual string NguonGocXeCu { get; set; }
	    public virtual int LoaiXeCu { get; set; }
	    public virtual int HienTrangSuDungCu { get; set; }
	}

    /// <summary>
    /// A class which represents the ThayDoiThongTin_Tren500 table.
    /// </summary>
	[Table("ThayDoiThongTin_Tren500")]
	public partial class ThayDoiThongTinTren500
	{
	    public virtual int ThayDoiThongTinId { get; set; }
	    public virtual string KyHieuCu { get; set; }
	    public virtual int HienTrangSuDungCu { get; set; }
	}

    /// <summary>
    /// A class which represents the sysdiagrams table.
    /// </summary>
	[Table("sysdiagrams")]
	public partial class sysdiagram
	{
	    public virtual string name { get; set; }
	    public virtual int principal_id { get; set; }
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int diagram_id { get; set; }
	    public virtual int? version { get; set; }
	    public virtual byte[] definition { get; set; }
	}

    /// <summary>
    /// A class which represents the HaoMon table.
    /// </summary>
	[Table("HaoMon")]
	public partial class HaoMon
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int HaoMonId { get; set; }
	    public virtual string KyTinh { get; set; }
	    public virtual string SoChungTu { get; set; }
	    public virtual DateTime NgayChungTu { get; set; }
	    public virtual DateTime NgayHaoMon { get; set; }
	    public virtual string NoiDung { get; set; }
	    public virtual int? CoSoId { get; set; }
	    public virtual int? NguoiTao { get; set; }
	    public virtual DateTime? NgayTao { get; set; }
	    public virtual int? CtrVersion { get; set; }
	}

    /// <summary>
    /// A class which represents the KhoPhieuXuat table.
    /// </summary>
	[Table("KhoPhieuXuat")]
	public partial class KhoPhieuXuat
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int KhoPhieuXuatId { get; set; }
	    public virtual string SoPhieu { get; set; }
	    public virtual DateTime NgayXuat { get; set; }
	    public virtual string Loai { get; set; }
	    public virtual int KhoXuatId { get; set; }
	    public virtual int? KhoNhanId { get; set; }
	    public virtual string NguoiNhanHang { get; set; }
	    public virtual string LyDo { get; set; }
	    public virtual int? CoSoId { get; set; }
	    public virtual int? NguoiTao { get; set; }
	    public virtual DateTime? NgayTao { get; set; }
	    public virtual int? CtrVersion { get; set; }
	}

    /// <summary>
    /// A class which represents the KhoPhieuXuatChiTiet table.
    /// </summary>
	[Table("KhoPhieuXuatChiTiet")]
	public partial class KhoPhieuXuatChiTiet
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int KhoPhieuXuatChiTietId { get; set; }
	    public virtual int KhoPhieuXuatId { get; set; }
	    public virtual int TaiSanId { get; set; }
	    public virtual decimal? SoLuong { get; set; }
	    public virtual decimal? DonGia { get; set; }
	    public virtual decimal? GiaMua { get; set; }
	    public virtual decimal? GiaBan { get; set; }
	    public virtual int? NguonNganSachId { get; set; }
	    public virtual int? NhaCungCapId { get; set; }
	    public virtual string HangDung { get; set; }
	    public virtual string LoSanXuat { get; set; }
	}

    /// <summary>
    /// A class which represents the KeHoachMuaSam table.
    /// </summary>
	[Table("KeHoachMuaSam")]
	public partial class KeHoachMuaSam
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int MuaSamId { get; set; }
	    public virtual decimal Nam { get; set; }
	    public virtual string NoiDung { get; set; }
	    public virtual int? DuyetId { get; set; }
	    public virtual int? NguoiDuyet { get; set; }
	    public virtual int CoSoId { get; set; }
	    public virtual int? NguoiTao { get; set; }
	    public virtual DateTime? NgayTao { get; set; }
	    public virtual int? CtrVersion { get; set; }
	}

    /// <summary>
    /// A class which represents the NhomTaiSan table.
    /// </summary>
	[Table("NhomTaiSan")]
	public partial class NhomTaiSan
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int NhomId { get; set; }
	    public virtual string MaNhom { get; set; }
	    public virtual string TenNhom { get; set; }
	    public virtual string GhiChu { get; set; }
	    public virtual int? NguoiTao { get; set; }
	    public virtual DateTime? NgayTao { get; set; }
	    public virtual int? CtrVersion { get; set; }
	}

    /// <summary>
    /// A class which represents the GhiTang table.
    /// </summary>
	[Table("GhiTang")]
	public partial class GhiTang
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int GhiTangId { get; set; }
	    public virtual string SoChungTu { get; set; }
	    public virtual DateTime NgayChungTu { get; set; }
	    public virtual DateTime NgayGhiTang { get; set; }
	    public virtual string NoiDung { get; set; }
	    public virtual int? DuyetId { get; set; }
	    public virtual int? NguoiDuyet { get; set; }
	    public virtual int CoSoId { get; set; }
	    public virtual int? NguoiTao { get; set; }
	    public virtual DateTime? NgayTao { get; set; }
	    public virtual int? CtrVersion { get; set; }
	}

    /// <summary>
    /// A class which represents the KhoaSoLieu table.
    /// </summary>
	[Table("KhoaSoLieu")]
	public partial class KhoaSoLieu
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int KhoaSoLieuId { get; set; }
	    public virtual string ThangNam { get; set; }
	    public virtual string TrangThai { get; set; }
	}

    /// <summary>
    /// A class which represents the LoaiTaiSan table.
    /// </summary>
	[Table("LoaiTaiSan")]
	public partial class LoaiTaiSan
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int LoaiId { get; set; }
	    public virtual int NhomId { get; set; }
	    public virtual string MaLoai { get; set; }
	    public virtual string TenLoai { get; set; }
	    public virtual string GhiChu { get; set; }
	    public virtual int? NguoiTao { get; set; }
	    public virtual DateTime? NgayTao { get; set; }
	    public virtual int? CtrVersion { get; set; }
	}

    /// <summary>
    /// A class which represents the ThongSo table.
    /// </summary>
	[Table("ThongSo")]
	public partial class ThongSo
	{
		[Key]
	    public virtual int ThongSoId { get; set; }
	    public virtual string Loai { get; set; }
	    public virtual string Ten { get; set; }
	}

    /// <summary>
    /// A class which represents the GhiGiam table.
    /// </summary>
	[Table("GhiGiam")]
	public partial class GhiGiam
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int GhiGiamId { get; set; }
	    public virtual string SoChungTu { get; set; }
	    public virtual DateTime NgayChungTu { get; set; }
	    public virtual DateTime NgayGhiTang { get; set; }
	    public virtual int PhongBanId { get; set; }
	    public virtual string NoiDung { get; set; }
	    public virtual int? DuyetId { get; set; }
	    public virtual int? NguoiDuyet { get; set; }
	    public virtual int? CoSoId { get; set; }
	    public virtual int? NguoiTao { get; set; }
	    public virtual DateTime? NgayTao { get; set; }
	    public virtual int? CtrVersion { get; set; }
	}

    /// <summary>
    /// A class which represents the DieuChuyen table.
    /// </summary>
	[Table("DieuChuyen")]
	public partial class DieuChuyen
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int DieuChuyenId { get; set; }
	    public virtual string SoChungTu { get; set; }
	    public virtual DateTime NgayChungTu { get; set; }
	    public virtual DateTime NgayDieuChuyen { get; set; }
	    public virtual string GhiChu { get; set; }
	    public virtual int? DuyetId { get; set; }
	    public virtual int? NguoiDuyet { get; set; }
	    public virtual int? CoSoId { get; set; }
	    public virtual int? NguoiTao { get; set; }
	    public virtual DateTime? NgayTao { get; set; }
	    public virtual int? CtrVersion { get; set; }
	}

    /// <summary>
    /// A class which represents the HangSanXuat table.
    /// </summary>
	[Table("HangSanXuat")]
	public partial class HangSanXuat
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int HangSanXuatId { get; set; }
	    public virtual string MaHangSanXuat { get; set; }
	    public virtual string TenHangSanXuat { get; set; }
	    public virtual string GhiChu { get; set; }
	    public virtual int? NguoiTao { get; set; }
	    public virtual DateTime? NgayTao { get; set; }
	    public virtual int? CtrVersion { get; set; }
	}

    /// <summary>
    /// A class which represents the DeNghiTrangCap table.
    /// </summary>
	[Table("DeNghiTrangCap")]
	public partial class DeNghiTrangCap
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int DeNghiId { get; set; }
	    public virtual DateTime Ngay { get; set; }
	    public virtual string SoPhieu { get; set; }
	    public virtual int? PhanLoaiId { get; set; }
	    public virtual int? PhongBanId { get; set; }
	    public virtual string NoiDung { get; set; }
	    public virtual int? CoSoId { get; set; }
	    public virtual int? DuyetId { get; set; }
	    public virtual int? NguoiDuyet { get; set; }
	    public virtual int? NguoiTao { get; set; }
	    public virtual DateTime? NgayTao { get; set; }
	    public virtual int? CtrVersion { get; set; }
	}

    /// <summary>
    /// A class which represents the NhaCungCap table.
    /// </summary>
	[Table("NhaCungCap")]
	public partial class NhaCungCap
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int NhaCungCapId { get; set; }
	    public virtual string MaNhaCungCap { get; set; }
	    public virtual string TenNhaCungCap { get; set; }
	    public virtual string Nhom { get; set; }
	    public virtual string DienThoai { get; set; }
	    public virtual string DiDong { get; set; }
	    public virtual string MaSoThue { get; set; }
	    public virtual string TKNganHang { get; set; }
	    public virtual string TenNganHang { get; set; }
	    public virtual string DaiDien { get; set; }
	    public virtual string DiaChi { get; set; }
	    public virtual string GhiChu { get; set; }
	    public virtual int? CoSoId { get; set; }
	    public virtual int? NguoiTao { get; set; }
	    public virtual DateTime? NgayTao { get; set; }
	    public virtual int? CtrVersion { get; set; }
	}

    /// <summary>
    /// A class which represents the NuocSanXuat table.
    /// </summary>
	[Table("NuocSanXuat")]
	public partial class NuocSanXuat
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int NuocSanXuatId { get; set; }
	    public virtual string MaNuocSanXuat { get; set; }
	    public virtual string TenNuocSanXuat { get; set; }
	    public virtual string GhiChu { get; set; }
	    public virtual int? NguoiTao { get; set; }
	    public virtual DateTime? NgayTao { get; set; }
	    public virtual int? CtrVersion { get; set; }
	}

    /// <summary>
    /// A class which represents the NhanVien table.
    /// </summary>
	[Table("NhanVien")]
	public partial class NhanVien
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int NhanVienId { get; set; }
	    public virtual int PhongBanId { get; set; }
	    public virtual string MaNhanVien { get; set; }
	    public virtual string TenNhanVien { get; set; }
	    public virtual string ChucDanh { get; set; }
	    public virtual string DienThoai { get; set; }
	    public virtual string Email { get; set; }
	    public virtual string DiaChi { get; set; }
	    public virtual string GhiChu { get; set; }
	    public virtual int? NguoiTao { get; set; }
	    public virtual DateTime? NgayTao { get; set; }
	    public virtual int? CtrVersion { get; set; }
	}

    /// <summary>
    /// A class which represents the DieuChuyenChiTiet table.
    /// </summary>
	[Table("DieuChuyenChiTiet")]
	public partial class DieuChuyenChiTiet
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int DieuChuyenChiTietId { get; set; }
	    public virtual int DieuChuyenId { get; set; }
	    public virtual int TaiSanId { get; set; }
	    public virtual int PhongBanSuDung { get; set; }
	    public virtual int PhongBanChuyenDen { get; set; }
	    public virtual decimal SoLuong { get; set; }
	    public virtual string LyDo { get; set; }
	}

    /// <summary>
    /// A class which represents the XuLy table.
    /// </summary>
	[Table("XuLy")]
	public partial class XuLy
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int XuLyId { get; set; }
	    public virtual string NoiDung { get; set; }
	}

    /// <summary>
    /// A class which represents the CoSo table.
    /// </summary>
	[Table("CoSo")]
	public partial class CoSo
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int CoSoId { get; set; }
	    public virtual string MaCoSo { get; set; }
	    public virtual int LoaiCoSoId { get; set; }
	    public virtual int? TrucThuoc { get; set; }
	    public virtual string TenCoSo { get; set; }
	    public virtual string DienThoai { get; set; }
	    public virtual string DiaChi { get; set; }
	    public virtual string GhiChu { get; set; }
	    public virtual int? NguoiTao { get; set; }
	    public virtual DateTime? NgayTao { get; set; }
	    public virtual int? CtrVersion { get; set; }
	}

    /// <summary>
    /// A class which represents the TheoDoi table.
    /// </summary>
	[Table("TheoDoi")]
	public partial class TheoDoi
	{
	    public virtual int TaiSanId { get; set; }
	    public virtual DateTime? NgayTrangCap { get; set; }
	    public virtual DateTime? NgayBatDauSuDung { get; set; }
	    public virtual int PhongBanId { get; set; }
	    public virtual int? NhanVienId { get; set; }
	    public virtual decimal? SLTon { get; set; }
	    public virtual decimal? SLTang { get; set; }
	    public virtual decimal? SLGiam { get; set; }
	}

    /// <summary>
    /// A class which represents the BienBanKiemKe table.
    /// </summary>
	[Table("BienBanKiemKe")]
	public partial class BienBanKiemKe
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int BienBanKiemKeId { get; set; }
	    public virtual string SoChungTu { get; set; }
	    public virtual DateTime NgayChungTu { get; set; }
	    public virtual DateTime NgayKiemKe { get; set; }
	    public virtual int PhongBanId { get; set; }
	    public virtual string GhiChu { get; set; }
	    public virtual int? CoSoId { get; set; }
	    public virtual int? NguoiTao { get; set; }
	    public virtual DateTime? NgayTao { get; set; }
	    public virtual int? CtrVersion { get; set; }
	}

    /// <summary>
    /// A class which represents the ThongTinCongKhai table.
    /// </summary>
	[Table("ThongTinCongKhai")]
	public partial class ThongTinCongKhai
	{
	    public virtual int TaiSanId { get; set; }
	    public virtual string MoTa { get; set; }
	    public virtual string MucDich { get; set; }
	    public virtual int? HienTrangSuDungId { get; set; }
	    public virtual decimal? DonGia { get; set; }
	    public virtual decimal? NopNganSach { get; set; }
	    public virtual decimal? DeLaiDonVi { get; set; }
	    public virtual decimal? HHCK { get; set; }
	    public virtual int? NhaCungCapId { get; set; }
	}

    /// <summary>
    /// A class which represents the BanKiemKe table.
    /// </summary>
	[Table("BanKiemKe")]
	public partial class BanKiemKe
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int BanKiemKeId { get; set; }
	    public virtual int BienBanKiemKeId { get; set; }
	    public virtual string NguoiKiemKe { get; set; }
	    public virtual string ChucVu { get; set; }
	    public virtual string DaiDien { get; set; }
	    public virtual string VaiTro { get; set; }
	}

    /// <summary>
    /// A class which represents the HienTrangSuDung table.
    /// </summary>
	[Table("HienTrangSuDung")]
	public partial class HienTrangSuDung
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int HienTrangSuDungId { get; set; }
	    public virtual string NoiDung { get; set; }
	}

    /// <summary>
    /// A class which represents the BienBanKiemKeChiTiet table.
    /// </summary>
	[Table("BienBanKiemKeChiTiet")]
	public partial class BienBanKiemKeChiTiet
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int BienBanKiemKeChiTietId { get; set; }
	    public virtual int BienBanKiemKeId { get; set; }
	    public virtual int TaiSanId { get; set; }
	    public virtual decimal SoLuong { get; set; }
	}

    /// <summary>
    /// A class which represents the KhaiThac table.
    /// </summary>
	[Table("KhaiThac")]
	public partial class KhaiThac
	{
		[Key]
	    public virtual int KhaiThacId { get; set; }
	    public virtual int TaiSanId { get; set; }
	    public virtual int KhachHangNCCId { get; set; }
	    public virtual string SoChungTu { get; set; }
	    public virtual decimal SoLuongKhaiThac { get; set; }
	    public virtual decimal DonGiaKhaiThac { get; set; }
	    public virtual DateTime ThoiGianBatDau { get; set; }
	    public virtual DateTime ThoiGianKetThuc { get; set; }
	    public virtual decimal? TienThu { get; set; }
	    public virtual decimal? NopNganSach { get; set; }
	    public virtual decimal? DonVi { get; set; }
	    public virtual string GhiChu { get; set; }
	    public virtual int? CoSoId { get; set; }
	    public virtual int? NguoiTao { get; set; }
	    public virtual DateTime? NgayTao { get; set; }
	    public virtual int? CtrVersion { get; set; }
	}

    /// <summary>
    /// A class which represents the KhachHang table.
    /// </summary>
	[Table("KhachHang")]
	public partial class KhachHang
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int KhachHangId { get; set; }
	    public virtual string MaKhachHang { get; set; }
	    public virtual string TenKhachHang { get; set; }
	    public virtual string DienThoai { get; set; }
	    public virtual string DiDong { get; set; }
	    public virtual string MaSoThue { get; set; }
	    public virtual string TKNganHang { get; set; }
	    public virtual string TenNganHang { get; set; }
	    public virtual string DiaChi { get; set; }
	    public virtual string GhiChu { get; set; }
	    public virtual int? CoSoId { get; set; }
	    public virtual int? NguoiTao { get; set; }
	    public virtual DateTime? NgayTao { get; set; }
	    public virtual int? CtrVersion { get; set; }
	}

    /// <summary>
    /// A class which represents the BaoDuong table.
    /// </summary>
	[Table("BaoDuong")]
	public partial class BaoDuong
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int BaoDuongId { get; set; }
	    public virtual int TaiSanId { get; set; }
	    public virtual DateTime? NgayBaoDuong { get; set; }
	    public virtual DateTime NgayDuKien { get; set; }
	    public virtual decimal DuToan { get; set; }
	    public virtual int LoaiBaoDuongId { get; set; }
	    public virtual string MoTa { get; set; }
	    public virtual int? DuyetId { get; set; }
	    public virtual int? NguoiDuyet { get; set; }
	    public virtual int? CoSoId { get; set; }
	    public virtual int? NguoiTao { get; set; }
	    public virtual DateTime? NgayTao { get; set; }
	    public virtual int? CtrVersion { get; set; }
	}

    /// <summary>
    /// A class which represents the ThayDoiThongTin table.
    /// </summary>
	[Table("ThayDoiThongTin")]
	public partial class ThayDoiThongTin
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int ThayDoiThongTinId { get; set; }
	    public virtual int TaiSanId { get; set; }
	    public virtual DateTime Ngay { get; set; }
	    public virtual string TenTaiSanCu { get; set; }
	    public virtual string LyDo { get; set; }
	    public virtual int? DuyetId { get; set; }
	    public virtual int? NguoiDuyet { get; set; }
	    public virtual int? CoSoId { get; set; }
	    public virtual int? NguoiTao { get; set; }
	    public virtual DateTime? NgayTao { get; set; }
	    public virtual int? CtrVersion { get; set; }
	}

    /// <summary>
    /// A class which represents the SuDung table.
    /// </summary>
	[Table("SuDung")]
	public partial class SuDung
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int SuDungId { get; set; }
	    public virtual int KyLap { get; set; }
	    public virtual decimal Nam { get; set; }
	    public virtual string NoiDung { get; set; }
	    public virtual int? CoSoId { get; set; }
	    public virtual int? NguoiTao { get; set; }
	    public virtual DateTime? NgayTao { get; set; }
	    public virtual int? CtrVersion { get; set; }
	}

    /// <summary>
    /// A class which represents the PhanLoai table.
    /// </summary>
	[Table("PhanLoai")]
	public partial class PhanLoai
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int PhanLoaiId { get; set; }
	    public virtual string TenPhanLoai { get; set; }
	}

    /// <summary>
    /// A class which represents the DuAn table.
    /// </summary>
	[Table("DuAn")]
	public partial class DuAn
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int DuAnId { get; set; }
	    public virtual string MaDuAn { get; set; }
	    public virtual string TenDuAn { get; set; }
	    public virtual string GhiChu { get; set; }
	    public virtual int? NgungTheoDoi { get; set; }
	    public virtual int? CoSoId { get; set; }
	    public virtual int? NguoiTao { get; set; }
	    public virtual DateTime? NgayTao { get; set; }
	    public virtual int? CtrVersion { get; set; }
	}

    /// <summary>
    /// A class which represents the DanhGia_NguyenGia table.
    /// </summary>
	[Table("DanhGia_NguyenGia")]
	public partial class DanhGiaNguyenGia
	{
	    public virtual int DanhGiaId { get; set; }
	    public virtual int NguonNganSachId { get; set; }
	    public virtual decimal GiaTriCu { get; set; }
	}

    /// <summary>
    /// A class which represents the DanhGia table.
    /// </summary>
	[Table("DanhGia")]
	public partial class DanhGia
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int DanhGiaId { get; set; }
	    public virtual string SoChungTu { get; set; }
	    public virtual DateTime NgayChungTu { get; set; }
	    public virtual DateTime NgayDanhGia { get; set; }
	    public virtual string NoiDung { get; set; }
	    public virtual int TaiSanId { get; set; }
	    public virtual decimal HaoMonLuyKeCu { get; set; }
	    public virtual int SoNamSuDungCu { get; set; }
	    public virtual decimal TyLeHaoMonCu { get; set; }
	    public virtual decimal? SLTonCu { get; set; }
	    public virtual int? CoSoId { get; set; }
	    public virtual int? NguoiTao { get; set; }
	    public virtual int? NgayTao { get; set; }
	}

    /// <summary>
    /// A class which represents the NguonNganSach table.
    /// </summary>
	[Table("NguonNganSach")]
	public partial class NguonNganSach
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int NguonNganSachId { get; set; }
	    public virtual string MaNguonNganSach { get; set; }
	    public virtual string TenNguonNganSach { get; set; }
	    public virtual string GhiChu { get; set; }
	    public virtual int? NguoiTao { get; set; }
	    public virtual DateTime? NgayTao { get; set; }
	    public virtual int? CtrVersion { get; set; }
	}

    /// <summary>
    /// A class which represents the LogData table.
    /// </summary>
	[Table("LogData")]
	public partial class LogData
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int LogId { get; set; }
	    public virtual DateTime? Ngay { get; set; }
	    public virtual string MaChucNang { get; set; }
	    public virtual int? DoiTuongId { get; set; }
	    public virtual string SuKien { get; set; }
	    public virtual string NoiDung { get; set; }
	    public virtual int? NguoiTao { get; set; }
	}

    /// <summary>
    /// A class which represents the TaiSan table.
    /// </summary>
	[Table("TaiSan")]
	public partial class TaiSan
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int TaiSanId { get; set; }
	    public virtual string MaTaiSan { get; set; }
	    public virtual string TenTaiSan { get; set; }
	    public virtual string DonViTinh { get; set; }
	    public virtual int LoaiId { get; set; }
	    public virtual int? PhuongThucId { get; set; }
	    public virtual decimal? NamSanXuat { get; set; }
	    public virtual int NuocSanXuatId { get; set; }
	    public virtual int? HangSanXuatId { get; set; }
	    public virtual string SoQDTC { get; set; }
	    public virtual string NhanHieu { get; set; }
	    public virtual int? DuAnId { get; set; }
	    public virtual DateTime NgayMua { get; set; }
	    public virtual DateTime NgayGhiTang { get; set; }
	    public virtual DateTime? NgayBDHaoMon { get; set; }
	    public virtual int? SoNamSuDung { get; set; }
	    public virtual decimal? TyLeHaoMon { get; set; }
	    public virtual decimal? HaoMonLuyKe { get; set; }
	    public virtual DateTime? NgayBDKhauHao { get; set; }
	    public virtual string KyTinhKhauHao { get; set; }
	    public virtual decimal? GiaTriKhauHao { get; set; }
	    public virtual decimal? SoKyKhauHao { get; set; }
	    public virtual decimal? TyLeKhauHao { get; set; }
	    public virtual decimal? KhauHaoLuyKe { get; set; }
	    public virtual int LoaiKeKhai { get; set; }
	    public virtual int CoSoId { get; set; }
	    public virtual int? NguoiTao { get; set; }
	    public virtual DateTime? NgayTao { get; set; }
	    public virtual int? CtrVersion { get; set; }
	}

    /// <summary>
    /// A class which represents the SuaChua table.
    /// </summary>
	[Table("SuaChua")]
	public partial class SuaChua
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int SuaChuaId { get; set; }
	    public virtual int BaoDuongId { get; set; }
	    public virtual string TenBoPhan { get; set; }
	    public virtual DateTime? NgayBatDau { get; set; }
	    public virtual DateTime? NgayKetThuc { get; set; }
	    public virtual decimal? ChiPhi { get; set; }
	    public virtual string NoiDung { get; set; }
	    public virtual string NoiSua { get; set; }
	    public virtual string KetQua { get; set; }
	}

    /// <summary>
    /// A class which represents the GhiTangChiTiet table.
    /// </summary>
	[Table("GhiTangChiTiet")]
	public partial class GhiTangChiTiet
	{
		[Key]
	    public virtual int _GhiTangChiTiet { get; set; }
	    public virtual int GhiTangId { get; set; }
	    public virtual int TaiSanId { get; set; }
	    public virtual DateTime? NgayBatDauSuDung { get; set; }
	    public virtual int? PhongBanId { get; set; }
	    public virtual int? NhanVienId { get; set; }
	    public virtual decimal SoLuong { get; set; }
	}

    /// <summary>
    /// A class which represents the SuDungChiTiet table.
    /// </summary>
	[Table("SuDungChiTiet")]
	public partial class SuDungChiTiet
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int _SuDungChiTiet { get; set; }
	    public virtual int SuDungId { get; set; }
	    public virtual int TaiSanId { get; set; }
	    public virtual decimal? SoSanPhamPhucVu { get; set; }
	    public virtual string DonViTinhSanPham { get; set; }
	    public virtual decimal? SoNguyenLieuSuDung { get; set; }
	    public virtual string DonViTinhNguyenLieu { get; set; }
	    public virtual string GhiChu { get; set; }
	}

    /// <summary>
    /// A class which represents the KhoTaiSan table.
    /// </summary>
	[Table("KhoTaiSan")]
	public partial class KhoTaiSan
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int KhoTaiSanId { get; set; }
	    public virtual int CoSoId { get; set; }
	    public virtual string MaKhoTaiSan { get; set; }
	    public virtual string TenKhoTaiSan { get; set; }
	    public virtual string GhiChu { get; set; }
	    public virtual int? NguoiTao { get; set; }
	    public virtual DateTime? NgayTao { get; set; }
	    public virtual int? CtrVersion { get; set; }
	}

    /// <summary>
    /// A class which represents the HaoMonChiTiet table.
    /// </summary>
	[Table("HaoMonChiTiet")]
	public partial class HaoMonChiTiet
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int HaoMonChiTietId { get; set; }
	    public virtual int HaoMonId { get; set; }
	    public virtual int TaiSanId { get; set; }
	    public virtual decimal TyLeHaoMonCu { get; set; }
	}

    /// <summary>
    /// A class which represents the BoTriSuDung table.
    /// </summary>
	[Table("BoTriSuDung")]
	public partial class BoTriSuDung
	{
		[Key]
	    public virtual int BoTriSuDungId { get; set; }
	    public virtual string NoiDung { get; set; }
	}

    /// <summary>
    /// A class which represents the KhoTonKho table.
    /// </summary>
	[Table("KhoTonKho")]
	public partial class KhoTonKho
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int KhoTonKhoId { get; set; }
	    public virtual int KhoTaiSanId { get; set; }
	    public virtual int CoSoId { get; set; }
	    public virtual string ThangNam { get; set; }
	    public virtual int TrangThai { get; set; }
	    public virtual int? NguoiTao { get; set; }
	    public virtual DateTime? NgayTao { get; set; }
	    public virtual int? CtrVersion { get; set; }
	}

    /// <summary>
    /// A class which represents the ThongTinKeKhai_Dat table.
    /// </summary>
	[Table("ThongTinKeKhai_Dat")]
	public partial class ThongTinKeKhaiDat
	{
	    public virtual int TaiSanId { get; set; }
	    public virtual string DiaChi { get; set; }
	    public virtual string GiayTo { get; set; }
	    public virtual decimal DienTich { get; set; }
	    public virtual decimal LamTruSo { get; set; }
	    public virtual decimal CoSoHDSuNghiep { get; set; }
	    public virtual decimal NhaO { get; set; }
	    public virtual decimal ChoThue { get; set; }
	    public virtual decimal BoTrong { get; set; }
	    public virtual decimal BiLanChiem { get; set; }
	    public virtual decimal SuDungKhac { get; set; }
	}

    /// <summary>
    /// A class which represents the PhuongThuc table.
    /// </summary>
	[Table("PhuongThuc")]
	public partial class PhuongThuc
	{
		[Key]
	    public virtual int PhuongThucId { get; set; }
	    public virtual string TenPhuongThuc { get; set; }
	}

    /// <summary>
    /// A class which represents the LoaiCoSo table.
    /// </summary>
	[Table("LoaiCoSo")]
	public partial class LoaiCoSo
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int LoaiCoSoId { get; set; }
	    public virtual string MaLoaiCoSo { get; set; }
	    public virtual string TenLoaiCoSo { get; set; }
	    public virtual string QuanHe { get; set; }
	    public virtual int? NguoiTao { get; set; }
	    public virtual DateTime? NgayTao { get; set; }
	    public virtual int? CtrVersion { get; set; }
	}

    /// <summary>
    /// A class which represents the HinhThuc table.
    /// </summary>
	[Table("HinhThuc")]
	public partial class HinhThuc
	{
		[Key]
	    public virtual int HinhThucId { get; set; }
	    public virtual string TenHinhThuc { get; set; }
	}

    /// <summary>
    /// A class which represents the GhiGiamChiTiet table.
    /// </summary>
	[Table("GhiGiamChiTiet")]
	public partial class GhiGiamChiTiet
	{
		[Key]
	    public virtual int GhiGiamChiTietId { get; set; }
	    public virtual int GhiGiamId { get; set; }
	    public virtual int TaiSanId { get; set; }
	    public virtual int XuLyId { get; set; }
	    public virtual decimal SoLuong { get; set; }
	}

    /// <summary>
    /// A class which represents the ThongTinKeKhai_Nha table.
    /// </summary>
	[Table("ThongTinKeKhai_Nha")]
	public partial class ThongTinKeKhaiNha
	{
	    public virtual int TaiSanId { get; set; }
	    public virtual string DiaChi { get; set; }
	    public virtual string GiayTo { get; set; }
	    public virtual int CapHang { get; set; }
	    public virtual int SoTang { get; set; }
	    public virtual decimal NamSuDung { get; set; }
	    public virtual decimal DienTich { get; set; }
	    public virtual decimal TongDienTichSan { get; set; }
	    public virtual decimal LamTruSo { get; set; }
	    public virtual decimal CoSoHDSuNghiep { get; set; }
	    public virtual decimal NhaO { get; set; }
	    public virtual decimal ChoThue { get; set; }
	    public virtual decimal BoTrong { get; set; }
	    public virtual decimal BiLanChiem { get; set; }
	    public virtual decimal SuDungKhac { get; set; }
	}

    /// <summary>
    /// A class which represents the KeHoachMuaSamChiTiet table.
    /// </summary>
	[Table("KeHoachMuaSamChiTiet")]
	public partial class KeHoachMuaSamChiTiet
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int MuaSamChiTietId { get; set; }
	    public virtual int MuaSamId { get; set; }
	    public virtual string TenTaiSan { get; set; }
	    public virtual int LoaiId { get; set; }
	    public virtual int PhuongThucId { get; set; }
	    public virtual string DonViTinh { get; set; }
	    public virtual string MoTa { get; set; }
	    public virtual DateTime Ngay { get; set; }
	    public virtual decimal SoLuong { get; set; }
	    public virtual decimal DonGia { get; set; }
	    public virtual int HinhThucId { get; set; }
	    public virtual decimal? DuToan { get; set; }
	    public virtual string GhiChu { get; set; }
	}

    /// <summary>
    /// A class which represents the KhoPhieuNhapChiTiet table.
    /// </summary>
	[Table("KhoPhieuNhapChiTiet")]
	public partial class KhoPhieuNhapChiTiet
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int KhoPhieuNhapChiTietId { get; set; }
	    public virtual int KhoPhieuNhapId { get; set; }
	    public virtual int TaiSanId { get; set; }
	    public virtual decimal SoLuong { get; set; }
	    public virtual decimal DonGia { get; set; }
	    public virtual decimal? GiaMua { get; set; }
	    public virtual decimal? GiaBan { get; set; }
	    public virtual decimal? VAT { get; set; }
	    public virtual string HangDung { get; set; }
	    public virtual string LoSanXuat { get; set; }
	}

    /// <summary>
    /// A class which represents the PhongBan table.
    /// </summary>
	[Table("PhongBan")]
	public partial class PhongBan
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int PhongBanId { get; set; }
	    public virtual int CoSoId { get; set; }
	    public virtual string MaPhongBan { get; set; }
	    public virtual string TenPhongBan { get; set; }
	    public virtual string GhiChu { get; set; }
	    public virtual int? NguoiTao { get; set; }
	    public virtual DateTime? NgayTao { get; set; }
	    public virtual int? CtrVersion { get; set; }
	}

    /// <summary>
    /// A class which represents the NguyenGia table.
    /// </summary>
	[Table("NguyenGia")]
	public partial class NguyenGia
	{
		[Key]
	    public virtual int TaiSanId { get; set; }
		[Key]
	    public virtual int NguonNganSachId { get; set; }
	    public virtual decimal? GiaTri { get; set; }
	}

    /// <summary>
    /// A class which represents the KhoTonKhoChiTiet table.
    /// </summary>
	[Table("KhoTonKhoChiTiet")]
	public partial class KhoTonKhoChiTiet
	{
		[Key]
	    public virtual int _KhoTonKhoChiTiet { get; set; }
	    public virtual int KhoTonKhoId { get; set; }
	    public virtual int TaiSanId { get; set; }
	    public virtual decimal DonGia { get; set; }
	    public virtual decimal? GiaMua { get; set; }
	    public virtual decimal? GiaBan { get; set; }
	    public virtual decimal? TonDau { get; set; }
	    public virtual decimal? SLNhap { get; set; }
	    public virtual decimal? SLXuat { get; set; }
	    public virtual int? NguonNganSachId { get; set; }
	    public virtual int? NhaCungCapId { get; set; }
	    public virtual string HangDung { get; set; }
	    public virtual string LoSanXuat { get; set; }
	}

}

